# Generated by Django 5.2 on 2025-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload a photo for your listing.', null=True, upload_to='service_images/'),
        ),
    ]
